name: CI Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment variables
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          TOUR_API_KEY: ${{ secrets.TOUR_API_KEY }}
          KAKAO_LOCAL_API_KEY: ${{secrets.KAKAO_LOCAL_API_KEY}}
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}

      - name: Build with Gradle
        run: ./gradlew build
